# Generated by Django 5.0.4 on 2024-05-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ingredient_typecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
